export const AppErrors = {
  // Generic
  VALIDATION_ERROR:        'VALIDATION_ERROR',
  NOT_FOUND:               'NOT_FOUND',
  FORBIDDEN:               'FORBIDDEN',
  // Auth
  NOT_AUTHENTICATED:       'NOT_AUTHENTICATED',
  INVALID_CREDENTIALS:     'INVALID_CREDENTIALS',
  NO_REFRESH_TOKEN:        'NO_REFRESH_TOKEN',
  REFRESH_TOKEN_INVALID:   'REFRESH_TOKEN_INVALID',
  TOKEN_INVALID:           'TOKEN_INVALID',
  // Products
  DOCUMENT_NOT_FOUND:      'DOCUMENT_NOT_FOUND',
  DOC_TYPE_RESTRICTED:     'DOC_TYPE_RESTRICTED',
  PRODUCT_ACCESS_DENIED:   'PRODUCT_ACCESS_DENIED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  // Companies
  COMPANY_NOT_FOUND:       'COMPANY_NOT_FOUND',
  COMPANY_KEY_EXISTS:      'COMPANY_KEY_EXISTS',
  COMPANY_DOCUMENT_NOT_FOUND: 'COMPANY_DOCUMENT_NOT_FOUND',
  COMPANY_DOC_UPLOAD_FAILED:  'COMPANY_DOC_UPLOAD_FAILED',
  // Quotations
  QUOTATION_NOT_FOUND:     'QUOTATION_NOT_FOUND',
  // Batches
  BATCH_NOT_FOUND:         'BATCH_NOT_FOUND',
  // Inventory
  ITEM_NOT_FOUND:          'ITEM_NOT_FOUND',
  // Vendors
  VENDOR_NOT_FOUND:        'VENDOR_NOT_FOUND',
  // Vendor material prices
  VENDOR_PRICE_INVALID_EFFECTIVE_DATE: 'VENDOR_PRICE_INVALID_EFFECTIVE_DATE',
  // Purchase entries
  PURCHASE_ENTRY_NOT_FOUND: 'PURCHASE_ENTRY_NOT_FOUND',
  PRICE_NOT_AVAILABLE:      'PRICE_NOT_AVAILABLE',
  // Staff
  STAFF_NOT_FOUND:         'STAFF_NOT_FOUND',
  // Salary records
  SALARY_RECORD_NOT_FOUND: 'SALARY_RECORD_NOT_FOUND',
  // Hazard profiles
  HAZARD_PROFILE_NOT_FOUND: 'HAZARD_PROFILE_NOT_FOUND',
  // Finished goods / dispatches
  FINISHED_GOODS_NOT_FOUND:   'FINISHED_GOODS_NOT_FOUND',
  FINISHED_GOODS_ALREADY_EXISTS: 'FINISHED_GOODS_ALREADY_EXISTS',
  DISPATCH_NOT_FOUND:         'DISPATCH_NOT_FOUND',
  DISPATCH_INSUFFICIENT_STOCK: 'DISPATCH_INSUFFICIENT_STOCK',
  DISPATCH_ALREADY_VOIDED:    'DISPATCH_ALREADY_VOIDED',
  DISPATCH_BATCH_CANCELLED:   'DISPATCH_BATCH_CANCELLED',
  // Customer purchase orders
  CUSTOMER_ORDER_NOT_FOUND:            'CUSTOMER_ORDER_NOT_FOUND',
  CUSTOMER_ORDER_ITEM_NOT_FOUND:       'CUSTOMER_ORDER_ITEM_NOT_FOUND',
  CUSTOMER_ORDER_DOCUMENT_NOT_FOUND:   'CUSTOMER_ORDER_DOCUMENT_NOT_FOUND',
  CUSTOMER_ORDER_DOC_UPLOAD_FAILED:    'CUSTOMER_ORDER_DOC_UPLOAD_FAILED',
  CUSTOMER_ORDER_INVALID_STATUS_TRANSITION: 'CUSTOMER_ORDER_INVALID_STATUS_TRANSITION',
  CUSTOMER_ORDER_ALREADY_CANCELLED:    'CUSTOMER_ORDER_ALREADY_CANCELLED',
  CUSTOMER_ORDER_BATCH_LINK_EXCEEDS_QUANTITY: 'CUSTOMER_ORDER_BATCH_LINK_EXCEEDS_QUANTITY',
  CUSTOMER_ORDER_BATCH_LINK_NOT_FOUND: 'CUSTOMER_ORDER_BATCH_LINK_NOT_FOUND',
  CUSTOMER_ORDER_LOCKED:               'CUSTOMER_ORDER_LOCKED',
} as const

export type AppError = typeof AppErrors[keyof typeof AppErrors]
